server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_cambio
    username: postgres
    password: root@123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:postgresql://localhost:5432/db_cambio
    user: postgres
    password: root@123
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
springdoc:
  show-actuator: true
  api-docs:
    path: cambio-service/v3/api-docs
  swagger-ui:
    config-url: /cambio-service/v3/api-docs/swagger-config
    url: /cambio-service/v3/api-docs